server:
  http:
    network: tcp
    addr: 0.0.0.0:10004
    timeout: 30s
  grpc:
    network: tcp
    addr: 0.0.0.0:11004
    timeout: 30s

data:
  database:
    driver: mysql
    host: "${DB_HOST:127.0.0.1}"
    port: "${DB_PORT:3306}"
    username: "${DB_USER:root}"
    password: "${DB_PASSWORD:root}"
    database: "${DB_NAME:chronoflow}"
    charset: utf8mb4
    parseTime: true
    loc: Local
  redis:
    network: tcp
    addr: "${REDIS_ADDR:127.0.0.1:6379}"
    read_timeout: 0.2s
    write_timeout: 0.2s

logging:
  level: INFO
  file:
    path: ./
    name: "chronoFlow-exec.log"
    maxSize: 10
    maxBackups: 5
    maxAge: 30
    compress: false
